apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: diabmotasem/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .

    - image: diabmotasem/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .

    - image: diabmotasem/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .


# apiVersion: skaffold/v2alpha3   # automate any change in infra files or in code or rebuild the image if change in dependencies
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local:
#     push: false         # whenever we build an image don't push it to docker hub which is the default 
#   artifacts:          # all the things that is going to be built
#     - image: diabmotasem/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:         # tells the skaffold how to handle any file that change
#         manual:
#           - src: 'src/**/*.ts'    # what to watch
#             dest: .         # where to sync this file to inside of our running container

# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   local:
#     push: false
#   artifacts:
#     - image: stephengrider/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .