apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseorders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courseorders
  template:
    metadata:
      labels:
        app: courseorders
    spec:
      containers:
        - name: courseorders
          image: diabmotasem/courseorders
          env:
            - name: MONGO_URI
              value: 'mongodb://courseorders-mongo-srv:27017/courseorders' 
            - name: JWT_KEY    # that can be seen inside the pod
              valueFrom:
                secretKeyRef:     # from did command
                  name: jwt-secret
                  key: JWT_KEY   
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # to be unique
---
apiVersion: v1
kind: Service
metadata:
  name: courseorders-srv
spec:
  selector:
    app: courseorders
  ports:
    - name: courseorders
      protocol: TCP
      port: 3000
      targetPort: 3000